#!/usr/bin/env zsh
# Shoutout to ThePrimeagen, code taken from: https://github.com/ThePrimeagen/.dotfiles/blob/master/clean-env

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "Installing $folder"
    stow -D $folder
    stow $folder

done

# Scripts I ran (sry, future me
# pip3 install pynvim neovim-remote
# https://github.com/pyenv/pyenv-virtualenv
